.PHONY: cert-manager.yaml

cert-manager.yaml:
	curl -sSL https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.yaml > cert-manager.yaml.1
	mv -f cert-manager.yaml.1 cert-manager.yaml


