apiVersion: k3d.io/v1alpha2
kind: Simple
name: k3d-kind
servers: 1
agents: 0
kubeAPI:
  hostIP: "100.101.28.3"
image: rancher/k3s:v1.21.4-k3s1
volumes:
  - volume: /tmp/data:/data
    nodeFilters:
      - all
ports:
  - port: 80:30080
    nodeFilters:
      - server[0]
  - port: 443:30443
    nodeFilters:
      - server[0]
  - port: 81:30081
    nodeFilters:
      - server[0]
options:
  k3d:
    wait: true
    timeout: "360s"
    disableLoadbalancer: true
    disableImageVolume: true
    disableHostIPInjection: true
  k3s:
    extraServerArgs:
      - --tls-san=100.101.28.3
      - --disable=traefik
    extraAgentArgs: []
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
