kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: 100.101.28.35
  apiServerPort: 6444
kubeadmConfigPatches:
  - |-
    kind: ClusterConfiguration
    metadata:
      name: config
    apiServer:
      certSANs:
        - localhost
        - 127.0.0.1
        - kubernetes
        - kubernetes.default.svc
        - kubernetes.default.svc.cluster.local
        - 100.101.28.35
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30681
        hostPort: 5681
      - containerPort: 30685
        hostPort: 5685
