# -*- mode: Python -*

analytics_settings(False)

k8s_yaml(kustomize('.'))

docker_build('katt-image', '.',
    live_update=[
        sync('.', '/app'),

        run('cd /app && pip install -r requirements.txt', trigger='./requirements.txt'),

        run('cd /app && sed -i "s/Hello cats!/{}/g" ./templates/index.html'. format("Congrats, you ran a live update!")),
])
