---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: home
  name: home
spec:
  serviceName: home
  replicas: 1
  selector:
    matchLabels:
      app: home
  volumeClaimTemplates: []
  template:
    metadata:
      labels:
        app: home
    spec:
      terminationGracePeriodSeconds: 60

      securityContext:
        fsGroup: 1001

      volumes:
      - name: docker
        hostPath:
          path: /var/run/docker.sock
      - name: mnt
        hostPath:
          path: /mnt

      containers:
      - name: home
        image: "defn/home:home"
        imagePullPolicy: Always
        ports:
        - containerPort: 2222
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock
        - name: mnt
          mountPath: /mnt
---
apiVersion: v1
kind: Service
metadata:
  name: home
  labels:
    app: home
  annotations:
    metallb.universe.tf/address-pool: general
    external-dns.alpha.kubernetes.io/hostname: home.ryokan.defn.jp
spec:
  type: LoadBalancer
  selector:
    app: home
  ports:
  - port: 22
    targetPort: 2222
